# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisDumper < Formula
  desc "CLI for export/import of redis keys to another redis instance, deletion of keys and dummy key generation."
  homepage "https://github.com/appit-online/redis-dumper"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.0/redis-dumper_1.0.0_macOS-ARM64.tar.gz"
      sha256 "496a0f6e3468fd25d9c77f9367ee47b22ab1f6c0e14f261b2f7dd0f877c273e7"

      def install
        bin.install "redis-dumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.0/redis-dumper_1.0.0_macOS-64bit.tar.gz"
      sha256 "ffd3bbeb355950a5502d7823a1ee1bfdbfb69affc4670063986adb13db9327d8"

      def install
        bin.install "redis-dumper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.0/redis-dumper_1.0.0_Linux-ARM64.tar.gz"
      sha256 "c69664dbbc8bc2b62783334cf2c1c397a6512f4d155c4770d82a136ad6864b98"

      def install
        bin.install "redis-dumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.0/redis-dumper_1.0.0_Linux-64bit.tar.gz"
      sha256 "6356b9e178e59112186171720710dd1ebd5b72fffcbe05b5d5d39a8116438cca"

      def install
        bin.install "redis-dumper"
      end
    end
  end
end
