# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisDumper < Formula
  desc "CLI for export/import of redis keys to another redis instance, deletion of keys and dummy key generation."
  homepage "https://github.com/appit-online/redis-dumper"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.5/redis-dumper_1.0.5_darwin-arm64.tar.gz"
      sha256 "3cfdc9d2bd1b0cf5ebd1e61d278971bfa76b82a1703a3f6f91d9095e81538440"

      def install
        bin.install "redis-dumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.5/redis-dumper_1.0.5_darwin-amd64.tar.gz"
      sha256 "74e434b20bfd871af7c4bd074c48d48bb999004c960feef002ec3c5c7836dd7c"

      def install
        bin.install "redis-dumper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.5/redis-dumper_1.0.5_linux-arm.tar.gz"
      sha256 "3d5d838737a8a78eef6f733a857e43a4f047f2943cb9bede37938998f79d4aa9"

      def install
        bin.install "redis-dumper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.5/redis-dumper_1.0.5_linux-arm64.tar.gz"
      sha256 "a8cdff27d528ffbd056f0ef0d265b502a4fbd034bbd25cfb248512b2dce3a6cf"

      def install
        bin.install "redis-dumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/appit-online/redis-dumper/releases/download/v1.0.5/redis-dumper_1.0.5_linux-amd64.tar.gz"
      sha256 "60975a498ae0cb78abc03a9d10cc9becbb112198ad7e1187c2d9bc7c50712d02"

      def install
        bin.install "redis-dumper"
      end
    end
  end
end
